[package]
name = "tangara-gen-tests"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tangara = { version = "0.1.0", path = "../tangara" }

[build-dependencies]
tangara = { version = "0.1.0", path = "../tangara", features = ["gen"] }
