// This file was generated by tangara-gen
// All changes in this file will discard after rebuilding project
use tangara::context::{Context, Ptr, Property};
pub enum EnumStruct {
}
pub enum EnumMixed {
}
pub enum EnumComplex {
}
pub trait MyTrait {
}
pub struct GenericsTest<T:MyTrait>;
pub struct TestStruct;
pub struct MyStruct;
pub fn load_MyLib(ctx: &Context) {
	let MyLib_package = ctx.get_package(17442259264759129316);
}
